**Referencias**

https://www.youtube.com/watch?v=JL9RMCS4Sho

https://www.youtube.com/watch?v=PqiwVp53ftU

**Carga de librerías**

In [93]:
import pandas as pd
import openpyxl
from openpyxl import load_workbook
from openpyxl import workbook
from openpyxl.styles import Font 
from openpyxl.chart import BarChart, LineChart, Reference
import string
import plotly
import plotly.graph_objects as go


#import mathplotlib

**Cargar datos desde página de Banco Mundial**

In [94]:
# Carga de los datos originales
df = pd.read_excel("https://api.worldbank.org/v2/es/indicator/FP.CPI.TOTL.ZG?downloadformat=excel", sheet_name= "Data", header= 3)

**Información a considerar por año**

In [95]:
# Datos en un período seleccionado: 2000 - 2020
df_selec_anio = df.drop(columns=['Country Code', 'Indicator Name', 'Indicator Code', '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999'])
anio = df_selec_anio.round(2)

**Información a considerar por país**

In [96]:
# Datos para un grupo de países seleccionados:
df_selec_pais = anio

lista_paises = ['Estados Unidos', 'Canadá', 'México', 'Costa Rica', 'Guatemala', 'Honduras', 'Nicaragua', 'Panamá', 'El Salvador', 'República Dominicana', 'Uruguay', 'Bolivia', 'Brasil', 'Chile', 'Colombia', 'Perú', 'Paraguay', 
]
filtro = df_selec_pais["Country Name"].apply(lambda pais: pais in lista_paises)
salida = df_selec_pais.loc[filtro, :]
#salida.style.set_properties(**{'border': '1.3px black','color': 'magenta'})
#salida.style.set_precision(2)

salida.style.set_table_styles([{"selector":"thead","props":"background-color:black; color:white;"},
                                {"selector":"th.row_heading", "props": [("background-color", "gray"), ("color", "white"),
                                          ("border", "3px solid black"), ("font-size", "1.2rem"), ("font-style", "italic")]},]).set_precision(2)

C:\Users\Tito\AppData\Local\Temp/ipykernel_6844/3914595404.py:11: FutureWarning: this method is deprecated in favour of `Styler.format(precision=..)`
  salida.style.set_table_styles([{"selector":"thead","props":"background-color:black; color:white;"},

**Estadística Descriptiva**

In [97]:
est_descrip = salida.describe()
est_descrip.style.set_table_styles([{"selector":"thead","props":"background-color:black; color:white;"},
                                {"selector":"th.row_heading", "props": [("background-color", "gray"), ("color", "white"),
                                          ("border", "3px solid black"), ("font-size", "1.2rem"), ("font-style", "italic")]},]).set_precision(2)


#est_descrip.round(2)

C:\Users\Tito\AppData\Local\Temp/ipykernel_6844/405496308.py:2: FutureWarning: this method is deprecated in favour of `Styler.format(precision=..)`
  est_descrip.style.set_table_styles([{"selector":"thead","props":"background-color:black; color:white;"},

In [98]:
grafica_1 = salida.T
grafica_1

,28,29,35,39,45,48,59,92,97,154,175,185,186,195,211,250,251
Country Name,Bolivia,Brasil,Canadá,Chile,Colombia,Costa Rica,República Dominicana,Guatemala,Honduras,México,Nicaragua,Panamá,Perú,Paraguay,El Salvador,Uruguay,Estados Unidos
2000,4.61,7.04,2.72,3.84,9.22,10.96,7.72,5.98,11.05,9.49,7.07,1.5,3.76,8.98,2.27,4.76,3.38
2001,1.59,6.84,2.53,3.57,7.97,11.26,8.88,7.29,9.67,6.37,5.99,0.31,1.98,7.27,3.75,4.36,2.83
2002,0.93,8.45,2.26,2.49,6.35,9.17,5.22,8.13,7.69,5.03,3.75,1.01,0.19,10.51,1.87,13.97,1.59
2003,3.34,14.71,2.76,2.81,7.13,9.45,27.45,5.6,7.67,4.55,5.3,0.39,2.26,14.24,2.12,19.38,2.27
2004,4.44,6.6,1.86,1.05,5.9,12.31,51.46,7.58,8.11,4.69,8.47,0.47,3.66,4.32,4.45,9.16,2.68
2005,5.39,6.87,2.21,3.05,5.05,13.8,4.19,9.11,8.81,3.99,9.6,2.86,1.62,6.81,4.69,4.7,3.39
2006,4.28,4.18,2.0,3.39,4.29,11.47,7.57,6.56,5.58,3.63,9.14,2.46,2.0,9.59,4.04,6.4,3.23
2007,8.71,3.64,2.14,4.41,5.55,9.36,6.14,6.82,6.94,3.97,11.13,4.17,1.78,8.13,4.58,8.11,2.85
2008,14.01,5.68,2.37,8.72,7.0,13.42,10.64,11.36,11.4,5.12,19.83,8.76,5.79,10.15,6.71,7.88,3.84
2009,3.35,4.89,0.3,0.35,4.2,7.84,1.44,1.86,5.5,5.3,3.69,2.41,2.94,2.59,1.06,7.06,-0.36
2010,2.5,5.04,1.78,1.41,2.27,5.66,6.33,3.86,4.7,4.16,5.46,3.49,1.53,4.65,1.18,6.7,1.64
2011,9.88,6.64,2.91,3.34,3.42,4.88,5.8,6.21,6.76,3.41,8.08,5.88,3.37,8.25,5.13,8.09,3.16
2012,4.52,5.4,1.52,3.01,3.17,4.5,3.69,3.78,5.2,4.11,7.19,5.7,3.66,3.68,1.73,8.1,2.07
2013,5.74,6.2,0.94,1.79,2.02,5.23,4.83,4.34,5.16,3.81,7.14,4.03,2.81,2.68,0.76,8.58,1.46
2014,5.77,6.33,1.91,4.72,2.9,4.52,3.0,3.42,6.13,4.02,6.04,2.63,3.24,5.03,1.14,8.88,1.62
2015,4.06,9.03,1.13,4.35,4.99,0.8,0.84,2.39,3.16,2.72,4.0,0.14,3.55,3.13,-0.73,8.67,0.12
2016,3.62,8.74,1.43,3.79,7.51,-0.02,1.61,4.45,2.72,2.82,3.52,0.74,3.59,4.09,0.6,9.64,1.26
2017,2.82,3.45,1.6,2.18,4.31,1.63,3.28,4.42,3.93,6.04,3.85,0.88,2.8,3.6,1.01,6.22,2.13
2018,2.27,3.66,2.27,2.43,3.24,2.22,3.56,3.75,4.35,4.9,4.95,0.76,1.32,3.98,1.09,7.61,2.44
2019,1.84,3.73,1.95,2.56,3.53,2.1,1.81,3.7,4.37,3.64,5.38,-0.36,2.14,2.76,0.08,7.88,1.81
2020,0.94,3.21,0.72,3.05,2.52,0.72,3.78,3.21,3.47,3.4,3.68,-1.55,1.83,1.77,-0.37,9.76,1.23

**Generando plantilla de Microsoft Excel**

In [116]:
nombre = "Reporte_2020"

In [117]:
# Creando un excel en blanco
data_null={}
df_null=pd.DataFrame(data_null)
df_null.to_excel(f"CPI_{nombre}.xlsx", index = False)

In [119]:
# Agregando pestañas al Excel
def automatizar_excel(nombre_archivo):

    nombre = nombre_archivo
    writer = pd.ExcelWriter(f"CPI_{nombre}.xlsx")

    salida.to_excel(writer, "CPI_Reporte", startcol=1, startrow=1, index=False)    
    
    est_descrip.to_excel(writer, "CPI_Reporte_Stats", startcol=1, startrow=1, index=True)

    grafica_1.to_excel(writer, "datos_graf", startcol=0, startrow=0, index=True)         

    writer.save()

    wb = load_workbook(f"CPI_{nombre}.xlsx")
    pestaña = wb["datos_graf"].sheet_state = 'hidden'   

    return

automatizar_excel(nombre)

In [120]:
def ocutlar(nombre_archivo):
    
    nombre = nombre_archivo
    wb = load_workbook(f"CPI_{nombre}.xlsx")
    pestaña = wb["datos_graf"].sheet_state = 'hidden'

    wb.save(f"CPI_{nombre}.xlsx")

    return

ocutlar(nombre)

In [36]:
# Agregando pestañas al Excel
#def automatizar_excel(nombre_archivo):

 #   nombre = nombre_archivo
  #  writer = pd.ExcelWriter(f"CPI_{nombre}.xlsx")

  #  salida.to_excel(writer, "CPI_Reporte", startcol=1, startrow=1, index=False)    
    
  #  est_descrip.to_excel(writer, "CPI_Reporte_Stats", startcol=1, startrow=1, index=True)

  #  writer.save()  

  #  return

#automatizar_excel("reporte_2020")

In [121]:
def graficar():
    
    wb = load_workbook(f"CPI_{nombre}.xlsx")
    pestaña = wb["datos_graf"]   

    min_col = wb.active.min_column
    max_col = wb.active.max_column
    min_fila = wb.active.min_row
    max_fila = wb.active.max_row

    barchart = LineChart()    
    data = Reference(pestaña, min_col=min_col, max_col=max_col-5, min_row=min_fila, max_row=max_fila+4)
    categorias = Reference(pestaña, min_col=min_col-1, max_col=min_col-1, min_row=min_fila+1, max_row=max_fila+4)

    barchart.add_data(data, titles_from_data=True)
    barchart.set_categories(categorias)
    
    pestaña_2 = wb["CPI_Reporte"]
    pestaña_2.add_chart(barchart, "B24")
    barchart.title = "CPI: Países Seleccionados"
    barchart.style = 2
    barchart.height = 15
    barchart.width = 20

    pestaña_2["B23"] = "Series de Tiempo"
    pestaña_2["B23"].font = Font("Arial", bold=True, size= 20)
    
    wb.save(f"CPI_{nombre}.xlsx")

graficar()